### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by akashhebbar** [EslamTK/GP#12]
Not able to login by the your given password

**Comment by imSunnyk** [comment]
> Not able to login by the your given password

hi,
 did you get database file ?

**Comment by EslamTK** [comment]
Hello Aakash,

You need to setup your local DB, the application is based on Django you can refer to [docs.djangoproject.com/en/2.0/intro/tutorial02/](Django Documentation) to setup your local DB and create an admin user to populate the application with data.
