### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by imSunnyk** [EslamTK/GP#14]
this issue is coming in browser
![Screenshot from 2020-10-05 18-53-05](https://user-images.githubusercontent.com/63893843/95084839-106dde00-073c-11eb-9d0b-a70eb90528bd.png)

plz help to solve

**Comment by EslamTK** [comment]
Hello Sunny,

As mentioned in the screenshot you need to add /dashboard or /login to the end of the url to open the application.
